/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{html,ts,scss}",
        "./src/app/**/*.{html,ts,scss}",
        "./src/**/**/*.html",
    ],
    theme: {
        colors: {
            "background": "#060e20",
            "primary": "#3fc2fb",
            "on-tertiary-container": "#3d5e00",
            "secondary": "#fe69ac",
            "secondary-fixed": "#ffc1d6",
            "on-surface": "#dee5ff",
            "on-error": "#490006",
            "inverse-on-surface": "#4d556b",
            "surface-container-high": "#141f38",
            "on-primary-fixed-variant": "#003e55",
            "primary-container": "#27b4ed",
            "outline": "#6d758c",
            "surface-container-highest": "#192540",
            "surface-dim": "#060e20",
            "surface-container-lowest": "#000000",
            "inverse-primary": "#00668a",
            "inverse-surface": "#faf8ff",
            "on-primary": "#00394f",
            "surface-variant": "#192540",
            "on-tertiary-fixed-variant": "#456900",
            "secondary-container": "#8c0152",
            "secondary-dim": "#fe69ac",
            "on-secondary-fixed": "#6b003d",
            "surface-container-low": "#091328",
            "tertiary-fixed": "#b8fd4b",
            "tertiary": "#e8ffc0",
            "surface-container": "#0f1930",
            "on-secondary-container": "#ffbfd5",
            "tertiary-container": "#b8fd4b",
            "on-secondary-fixed-variant": "#9a145d",
            "primary-fixed": "#36bdf6",
            "on-primary-fixed": "#001a27",
            "on-tertiary": "#446700",
            "secondary-fixed-dim": "#ffaccb",
            "surface-bright": "#1f2b49",
            "primary-dim": "#1aafe7",
            "on-error-container": "#ffa8a3",
            "error": "#ff716c",
            "on-tertiary-fixed": "#304a00",
            "on-secondary": "#460026",
            "on-background": "#dee5ff",
            "tertiary-dim": "#aaee3d",
            "error-dim": "#d7383b",
            "surface-tint": "#3fc2fb",
            "surface": "#060e20",
            "on-surface-variant": "#a3aac4",
            "error-container": "#9f0519",
            "on-primary-container": "#002e40",
            "primary-fixed-dim": "#1aafe7",
            "outline-variant": "#40485d",
            "tertiary-fixed-dim": "#aaee3d"
        },
        fontFamily: {
            "headline": ["Plus Jakarta Sans"],
            "body": ["Inter"],
            "label": ["Space Grotesk"]
        },
        borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
    },
    plugins: [],
}

